.TH "CDEK" 3 "Вт 28 Фев 2023" "Version 1.0.0.1" "CDEK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDEK
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Логика взаимодействия для App\&.xaml\&. "
.ti -1c
.RI "class \fBApplicationWin\fP"
.br
.RI "Логика взаимодействия для ApplicationWin\&.xaml\&. "
.ti -1c
.RI "class \fBDataSenderRecipient\fP"
.br
.ti -1c
.RI "class \fBDBConnect\fP"
.br
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "Логика взаимодействия для MainWindow\&.xaml\&. "
.ti -1c
.RI "class \fBReportWin\fP"
.br
.RI "ReportWin\&. "
.ti -1c
.RI "class \fBViewApplicationsWin\fP"
.br
.RI "ViewApplicationsWin\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для CDEK из исходного текста\&.
