.TH "CDEK.ReportWin" 3 "Вт 28 Фев 2023" "Version 1.0.0.1" "CDEK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDEK.ReportWin \- ReportWin\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:System\&.Windows\&.Window и System\&.Windows\&.Markup\&.IComponentConnector\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.in -1c
.SH "Подробное описание"
.PP 
ReportWin\&. 
.PP
См\&. определение в файле \fBReportWin\&.g\&.cs\fP строка \fB41\fP
.SH "Методы"
.PP 
.SS "void CDEK\&.ReportWin\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
См\&. определение в файле \fBReportWin\&.g\&.cs\fP строка \fB402\fP
.SS "void CDEK\&.ReportWin\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
См\&. определение в файле \fBReportWin\&.g\&.i\&.cs\fP строка \fB402\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для CDEK из исходного текста\&.
