.TH "CDEK.App" 3 "Вт 28 Фев 2023" "Version 1.0.0.1" "CDEK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDEK.App \- Логика взаимодействия для App\&.xaml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:Application и System\&.Windows\&.Application\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.in -1c
.SS "Открытые статические члены"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Application Entry Point\&. "
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Application Entry Point\&. "
.in -1c
.SH "Подробное описание"
.PP 
Логика взаимодействия для App\&.xaml\&. 

App\&. 
.PP
См\&. определение в файле \fBApp\&.xaml\&.cs\fP строка \fB14\fP
.SH "Методы"
.PP 
.SS "void CDEK\&.App\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
См\&. определение в файле \fBApp\&.g\&.cs\fP строка \fB48\fP
.SS "void CDEK\&.App\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
См\&. определение в файле \fBApp\&.g\&.i\&.cs\fP строка \fB48\fP
.SS "static void CDEK\&.App\&.Main ()\fC [static]\fP"

.PP
Application Entry Point\&. 
.PP
См\&. определение в файле \fBApp\&.g\&.cs\fP строка \fB63\fP
.SS "static void CDEK\&.App\&.Main ()\fC [static]\fP"

.PP
Application Entry Point\&. 
.PP
См\&. определение в файле \fBApp\&.g\&.i\&.cs\fP строка \fB63\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для CDEK из исходного текста\&.
