.TH "CDEK.MainWindow" 3 "Вт 28 Фев 2023" "Version 1.0.0.1" "CDEK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDEK.MainWindow \- Логика взаимодействия для MainWindow\&.xaml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:System\&.Windows\&.Window и System\&.Windows\&.Markup\&.IComponentConnector\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.in -1c
.SH "Подробное описание"
.PP 
Логика взаимодействия для MainWindow\&.xaml\&. 

MainWindow\&. 
.PP
См\&. определение в файле \fBMainWindow\&.xaml\&.cs\fP строка \fB22\fP
.SH "Конструктор(ы)"
.PP 
.SS "CDEK\&.MainWindow\&.MainWindow ()"

.PP
См\&. определение в файле \fBMainWindow\&.xaml\&.cs\fP строка \fB28\fP
.SH "Методы"
.PP 
.SS "void CDEK\&.MainWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
См\&. определение в файле \fBAutorization\&.g\&.i\&.cs\fP строка \fB58\fP
.SS "void CDEK\&.MainWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
См\&. определение в файле \fBMainWindow\&.g\&.cs\fP строка \fB130\fP
.SS "void CDEK\&.MainWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
См\&. определение в файле \fBMainWindow\&.g\&.i\&.cs\fP строка \fB130\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для CDEK из исходного текста\&.
