//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDEK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Application
    {
        public int id_Applications { get; set; }
        public string Firstname_sender { get; set; }
        public string Secondname_sender { get; set; }
        public string Number_phone_sender { get; set; }
        public string Type_package { get; set; }
        public string Adress_sender { get; set; }
        public string Firstname_recipient { get; set; }
        public string Secondname_recipient { get; set; }
        public string Number_phone_recipient { get; set; }
        public string Adress_recipient { get; set; }
        public string Email { get; set; }
    }
}
